package core

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CookieEntry represents a single cookie in Netscape format
type CookieEntry struct {
	Domain   string
	Flag     string
	Path     string
	Secure   string
	Expiry   string
	Name     string
	Value    string
}

// ParseCookieString parses a cookie string (name=value; name2=value2) into Netscape format
func ParseCookieString(cookieStr, domain string) []CookieEntry {
	if domain == "" {
		domain = ".youtube.com"
	}

	entries := []CookieEntry{}
	pairs := strings.Split(cookieStr, ";")

	// Default expiry: 1 year from now
	expiry := time.Now().Add(365 * 24 * time.Hour).Unix()

	for _, pair := range pairs {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}

		parts := strings.SplitN(pair, "=", 2)
		if len(parts) != 2 {
			continue
		}

		name := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		if name == "" {
			continue
		}

		// Determine if cookie should be secure based on name
		secure := "FALSE"
		if strings.HasPrefix(name, "__Secure-") || strings.Contains(name, "SAPISID") {
			secure = "TRUE"
		}

		entries = append(entries, CookieEntry{
			Domain: domain,
			Flag:   "TRUE",
			Path:   "/",
			Secure: secure,
			Expiry: fmt.Sprintf("%d", expiry),
			Name:   name,
			Value:  value,
		})
	}

	return entries
}

// WriteCookieFile writes cookies to a Netscape format file
func WriteCookieFile(entries []CookieEntry, filepath string) error {
	var sb strings.Builder
	sb.WriteString("# Netscape HTTP Cookie File\n")
	sb.WriteString("# This file was generated by DownAria-API\n")
	sb.WriteString("# Do not edit.\n\n")

	for _, entry := range entries {
		line := fmt.Sprintf("%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
			entry.Domain,
			entry.Flag,
			entry.Path,
			entry.Secure,
			entry.Expiry,
			entry.Name,
			entry.Value,
		)
		sb.WriteString(line)
	}

	return os.WriteFile(filepath, []byte(sb.String()), 0600)
}

// CreateTempCookieFile creates a temporary cookie file from cookie string
func CreateTempCookieFile(cookieStr, domain string) (string, error) {
	if cookieStr == "" {
		return "", nil
	}

	entries := ParseCookieString(cookieStr, domain)
	if len(entries) == 0 {
		return "", nil
	}

	// Create temp file
	tempDir := os.TempDir()
	tempFile := filepath.Join(tempDir, fmt.Sprintf("downaria_cookies_%d.txt", time.Now().UnixNano()))

	if err := WriteCookieFile(entries, tempFile); err != nil {
		return "", fmt.Errorf("failed to write cookie file: %w", err)
	}

	return tempFile, nil
}

// CleanupCookieFile removes temporary cookie file
func CleanupCookieFile(filepath string) {
	if filepath != "" {
		_ = os.Remove(filepath)
	}
}
